name: node js CI
on: [push]

jobs: #<-- starts the job encapsulation
  build: #<--start build job encapsulation
    runs-on: ubuntu-latest
    steps: #start steps encapsulation with in 'build' job
     - name: Checkout code
       uses: actions/checkout@v4
     - name: setup node.js
       uses: actions/setup-node@v4
       with: 
        node-version: 14
     - name: Run install
       run: npm install
     - name: install dependencies
       run: npm ci
     - name: run build
       run: npm run build
    #<--step are end with in build job
  #<-- end of build job encapsulation
  test: #<--start of test encapsulation
    needs: build
    runs-on: ubuntu-latest
    steps: #start steps encapsulation with in the 'test' job
     - name: checkout test code
       uses: actions/checkout@v4
     - name: setup node.js
       uses: actions/setup-node@v4
       with:
        node-version: 14
     - name: Run install
       run: npm install
     - name: install dependencies
       run: npm ci
     - name: run test
       run: npm test
    #<--end of steps in test job
  #<-- end of test job encapsulation
  
      
